#!/usr/bin/env python3
"""
Generates the Flyway migration that seeds the exercise catalog from free-exercise-db
(https://github.com/yuhonas/free-exercise-db, Unlicense).

The dataset has a single "shoulders" muscle. It is split into front, side and rear delts
by the exercise name, with a few manual overrides; see split_delts().

Usage: python3 generate_exercise_catalog.py > ../training-backend/src/main/resources/db/migration/V15__create_exercise_catalog.sql
Only regenerate a migration that has not been applied anywhere yet. Later catalog changes
need a new migration.
"""
import json
import re
import sys
import urllib.request

COMMIT = "f00c92c7dcf1216a928a52c3706c7ce8e2f71ed5"
URL = f"https://raw.githubusercontent.com/yuhonas/free-exercise-db/{COMMIT}/dist/exercises.json"

# Stretching and cardio don't count towards hard sets per muscle
SKIPPED_CATEGORIES = {"stretching", "cardio"}

MUSCLES = {
    "abdominals": "ABDOMINALS",
    "abductors": "ABDUCTORS",
    "adductors": "ADDUCTORS",
    "biceps": "BICEPS",
    "calves": "CALVES",
    "chest": "CHEST",
    "forearms": "FOREARMS",
    "glutes": "GLUTES",
    "hamstrings": "HAMSTRINGS",
    "lats": "LATS",
    "lower back": "LOWER_BACK",
    "middle back": "MIDDLE_BACK",
    "neck": "NECK",
    "quadriceps": "QUADRICEPS",
    "traps": "TRAPS",
    "triceps": "TRICEPS",
}

# Exercises whose delt heads the name rules get wrong or can't tell
PRIMARY_DELT_OVERRIDES = {
    "Side Laterals to Front Raise": ["SIDE_DELTS", "FRONT_DELTS"],
    "Dumbbell Scaption": ["FRONT_DELTS", "SIDE_DELTS"],
    "Iron Cross": ["FRONT_DELTS", "SIDE_DELTS"],
    "Power Partials": ["SIDE_DELTS"],
    "Crucifix": ["SIDE_DELTS"],
}

REAR = re.compile(r"rear|reverse fly|reverse machine fly|back flyes|pull apart|face pull|bent[- ]over .*(lateral|raise)"
                  r"|external rotation|cuban press|row to neck", re.I)
SIDE = re.compile(r"lateral|upright|deltoid raise", re.I)
SECONDARY_SIDE = re.compile(r"shrug|upright|high pull", re.I)


def split_delts(exercise, primary):
    """Returns the delt heads for an exercise that lists shoulders as primary or secondary."""
    name = exercise["name"]
    if primary:
        if name in PRIMARY_DELT_OVERRIDES:
            return PRIMARY_DELT_OVERRIDES[name]
        if REAR.search(name):
            return ["REAR_DELTS"]
        if SIDE.search(name):
            return ["SIDE_DELTS"]
        # Presses, front raises and most overhead work
        return ["FRONT_DELTS"]
    if SECONDARY_SIDE.search(name):
        return ["SIDE_DELTS"]
    # Rows, pulldowns and pull-ups work the rear delts; presses, dips and flyes the front
    pulls = {"lats", "middle back"} & set(exercise["primaryMuscles"])
    if pulls and "pullover" not in name.lower():
        return ["REAR_DELTS"]
    return ["FRONT_DELTS"]


def muscles_of(exercise):
    roles = {}
    for role, key in (("PRIMARY", "primaryMuscles"), ("SECONDARY", "secondaryMuscles")):
        for muscle in exercise[key]:
            codes = split_delts(exercise, role == "PRIMARY") if muscle == "shoulders" else [MUSCLES[muscle]]
            for code in codes:
                # Some entries list a muscle twice; primary wins
                roles.setdefault(code, role)
    return roles


def sql(value):
    return "NULL" if value is None else "'" + value.replace("'", "''") + "'"


def main():
    with urllib.request.urlopen(URL) as response:
        exercises = json.load(response)
    exercises = sorted((e for e in exercises if e["category"] not in SKIPPED_CATEGORIES), key=lambda e: e["name"].lower())

    out = sys.stdout
    out.write(f"""-- ============================================================
-- Migration: Exercise catalog and muscle groups
--
-- A read-only catalog of common exercises with the muscles they train,
-- seeded from free-exercise-db ({COMMIT[:7]}, Unlicense). Generated by
-- backend/scripts/generate_exercise_catalog.py; don't edit by hand.
-- The dataset's "shoulders" is split into front, side and rear delts.
--
-- Library entries get their own muscle list, which users pick from the
-- catalog or set by hand. Weekly sets per muscle count a set once for
-- each primary muscle and half for each secondary one.
-- ============================================================

CREATE TABLE exercise_catalog (
    id        BIGSERIAL PRIMARY KEY,
    -- free-exercise-db id, for later migrations that update the catalog
    slug      VARCHAR(100) NOT NULL UNIQUE,
    name      VARCHAR(100) NOT NULL,
    equipment VARCHAR(30),
    category  VARCHAR(30) NOT NULL
);

CREATE TABLE exercise_catalog_muscles (
    catalog_exercise_id BIGINT NOT NULL REFERENCES exercise_catalog(id) ON DELETE CASCADE,
    muscle              VARCHAR(20) NOT NULL,
    role                VARCHAR(10) NOT NULL,
    PRIMARY KEY (catalog_exercise_id, muscle)
);

CREATE TABLE library_exercise_muscles (
    library_exercise_id BIGINT NOT NULL REFERENCES library_exercises(id) ON DELETE CASCADE,
    muscle              VARCHAR(20) NOT NULL,
    role                VARCHAR(10) NOT NULL,
    PRIMARY KEY (library_exercise_id, muscle)
);

""")
    muscle_list = ", ".join(f"'{m}'" for m in sorted(list(MUSCLES.values()) + ["FRONT_DELTS", "SIDE_DELTS", "REAR_DELTS"]))
    for table in ("exercise_catalog_muscles", "library_exercise_muscles"):
        out.write(f"ALTER TABLE {table}\n"
                  f"    ADD CONSTRAINT chk_{table}_muscle CHECK (muscle IN ({muscle_list})),\n"
                  f"    ADD CONSTRAINT chk_{table}_role CHECK (role IN ('PRIMARY', 'SECONDARY'));\n\n")

    out.write("INSERT INTO exercise_catalog (slug, name, equipment, category) VALUES\n")
    out.write(",\n".join(
        f"    ({sql(e['id'])}, {sql(e['name'])}, {sql(e['equipment'])}, {sql(e['category'])})" for e in exercises))
    out.write(";\n\n")

    out.write("INSERT INTO exercise_catalog_muscles (catalog_exercise_id, muscle, role)\n"
              "SELECT c.id, v.muscle, v.role\n"
              "FROM (VALUES\n")
    rows = [(e["id"], muscle, role) for e in exercises for muscle, role in muscles_of(e).items()]
    out.write(",\n".join(f"    ({sql(slug)}, '{muscle}', '{role}')" for slug, muscle, role in rows))
    out.write("\n) AS v(slug, muscle, role)\n"
              "JOIN exercise_catalog c ON c.slug = v.slug;\n\n")

    out.write("""-- ────────────────────────────────────────────────────────────
-- Backfill: library entries named exactly like a catalog exercise
-- (ignoring case) take over its muscles
-- ────────────────────────────────────────────────────────────
INSERT INTO library_exercise_muscles (library_exercise_id, muscle, role)
SELECT le.id, cm.muscle, cm.role
FROM library_exercises le
JOIN exercise_catalog c ON LOWER(c.name) = LOWER(TRIM(le.name))
JOIN exercise_catalog_muscles cm ON cm.catalog_exercise_id = c.id;
""")


if __name__ == "__main__":
    main()
