import { vars } from 'nativewind';

export const darkColors = {
  accent:       '#cafd00',
  accentFg:     '#0e0e0e',
  accentText:   '#cafd00',
  accentMuted:  '#1a2200',
  primary:      '#f5f5f5',
  muted:        '#7a7a7a',
  subtle:       '#262626',
  dim:          '#1a1a1a',
  danger:       '#ff734a',
  dangerMuted:  '#2a1410',
  info:         '#81ecff',
  base:         '#0e0e0e',
  surface:      '#131313',
  elevated:     '#1a1a1a',
  surfaceDone:  '#0d1408',
  border:       '#131313',
};

export const lightColors = {
  accent:       '#cafd00',
  accentFg:     '#0e0e0e',
  accentText:   '#4d6600',
  accentMuted:  '#e8f5d0',
  primary:      '#111111',
  muted:        '#666666',
  subtle:       '#bbbbbb',
  dim:          '#d0d0d0',
  danger:       '#cc3300',
  dangerMuted:  '#ffe5de',
  info:         '#0088bb',
  base:         '#f0f0f0',
  surface:      '#ffffff',
  elevated:     '#e4e4e4',
  surfaceDone:  '#eef5e8',
  border:       '#e4e4e4',
};

export const darkTheme = vars({
  '--color-accent':       darkColors.accent,
  '--color-accent-fg':    darkColors.accentFg,
  '--color-accent-text':  darkColors.accentText,
  '--color-accent-muted': darkColors.accentMuted,
  '--color-primary':      darkColors.primary,
  '--color-muted':        darkColors.muted,
  '--color-subtle':       darkColors.subtle,
  '--color-dim':          darkColors.dim,
  '--color-danger':       darkColors.danger,
  '--color-danger-muted': darkColors.dangerMuted,
  '--color-info':         darkColors.info,
  '--color-base':         darkColors.base,
  '--color-surface':      darkColors.surface,
  '--color-elevated':     darkColors.elevated,
  '--color-surface-done': darkColors.surfaceDone,
  '--color-border':       darkColors.border,
});

export const lightTheme = vars({
  '--color-accent':       lightColors.accent,
  '--color-accent-fg':    lightColors.accentFg,
  '--color-accent-text':  lightColors.accentText,
  '--color-accent-muted': lightColors.accentMuted,
  '--color-primary':      lightColors.primary,
  '--color-muted':        lightColors.muted,
  '--color-subtle':       lightColors.subtle,
  '--color-dim':          lightColors.dim,
  '--color-danger':       lightColors.danger,
  '--color-danger-muted': lightColors.dangerMuted,
  '--color-info':         lightColors.info,
  '--color-base':         lightColors.base,
  '--color-surface':      lightColors.surface,
  '--color-elevated':     lightColors.elevated,
  '--color-surface-done': lightColors.surfaceDone,
  '--color-border':       lightColors.border,
});
